workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: LOOP CRM
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.loopcrm.mobile
      groups:
        - ios_config # BASE_URL, API_KEY, and GOOGLE_SERVICE_INFO_PLIST
      vars:
        APP_ID: "com.loopcrm.mobile"
        APP_STORE_ID: "6758578493" # سيتم ملؤه لاحقاً بعد إنشاء التطبيق في App Store Connect
        BUNDLE_ID: "com.loopcrm.mobile"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_MODE: "release"
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "2"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Create .env file for production
        script: |
          echo "BASE_URL=$BASE_URL" > .env
          echo "API_KEY=$API_KEY" >> .env
          echo "✅ Created .env file with production settings"
          cat .env
      - name: Create GoogleService-Info.plist for Firebase
        script: |
          if [ -n "$GOOGLE_SERVICE_INFO_PLIST" ]; then
            echo "$GOOGLE_SERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist
            echo "✅ Created GoogleService-Info.plist from environment variable"
          else
            echo "⚠️ Warning: GOOGLE_SERVICE_INFO_PLIST not set. Firebase push notifications may not work."
          fi
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Create ExportOptions.plist with installed profile name
        script: |
          cd "$CM_BUILD_DIR"
          PROFILE_NAME=""
          for f in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            [ -f "$f" ] || continue
            security cms -D -i "$f" > /tmp/profile_decoded.plist 2>/dev/null
            APPID=$(plutil -extract Entitlements.application-identifier raw /tmp/profile_decoded.plist 2>/dev/null)
            if echo "$APPID" | grep -q "com.loopcrm.mobile"; then
              PROFILE_NAME=$(plutil -extract Name raw /tmp/profile_decoded.plist 2>/dev/null)
              break
            fi
          done
          if [ -z "$PROFILE_NAME" ]; then
            echo "❌ No provisioning profile found for com.loopcrm.mobile"
            ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ 2>/dev/null || true
            exit 1
          fi
          echo "✅ Using provisioning profile: $PROFILE_NAME"
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict/></plist>' > /tmp/ExportOptions.plist
          /usr/libexec/PlistBuddy /tmp/ExportOptions.plist -c "Add :method string app-store" -c "Add :signingStyle string automatic" -c "Add :provisioningProfiles dict" -c "Add :provisioningProfiles:com.loopcrm.mobile string \"$PROFILE_NAME\""
          echo "✅ ExportOptions.plist created at /tmp/ExportOptions.plist"
      - name: Flutter build ipa
        script: |
          cd "$CM_BUILD_DIR"
          flutter build ipa \
            --release \
            --export-options-plist /tmp/ExportOptions.plist \
            --build-name="${FLUTTER_BUILD_NAME}" \
            --build-number="${FLUTTER_BUILD_NUMBER}"
          echo "=== After build: looking for IPA ==="
          ls -la build/ios/ipa/ 2>/dev/null || true
          find . -name "*.ipa" -type f 2>/dev/null || true
      - name: Copy IPA to export directory for artifacts
        script: |
          cd "$CM_BUILD_DIR"
          ROOT="${CM_BUILD_DIR:-.}"
          mkdir -p "$CM_EXPORT_DIR"
          IPA_PATH=$(find "$ROOT" -name "*.ipa" -type f 2>/dev/null | head -1)
          if [ -n "$IPA_PATH" ]; then
            cp "$IPA_PATH" "$CM_EXPORT_DIR/"
            echo "✅ IPA copied to $CM_EXPORT_DIR: $IPA_PATH"
            ls -la "$CM_EXPORT_DIR"
          else
            echo "⚠️ No .ipa found under $ROOT"
            echo "pwd=$(pwd) CM_BUILD_DIR=$CM_BUILD_DIR"
            ls -la build/ios/ 2>/dev/null || true
            find "$ROOT" -type d -name "ipa" 2>/dev/null || true
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hassan.alsaadi8@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
