import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Common
      "signIn": "Sign In",
      'appName': 'LOOP CRM',
      'welcome': 'Welcome to LOOP CRM',
      'manageLeadsInventory': 'Manage Leads and Inventory',
      'home': 'Home',
      'leads': 'Leads',
      'allLeads': 'All Leads',
      'freshLeads': 'Fresh Leads',
      'coldLeads': 'Cold Leads',
      'untouched': 'Untouched',
      'touched': 'Touched',
      'following': 'Following',
      'goodMorning': 'Good Morning',
      'readyForWork': 'Ready for Work, Make customers happy!',
      'typeToSearch': 'Type to search...',
      'add': 'Add',
      'addAction': 'Add Action',
      'addProduct': 'Add Product',
      'addProductCategory': 'Add Product Category',
      'addSupplier': 'Add Supplier',
      'addService': 'Add Service',
      'addServicePackage': 'Add Service Package',
      'addServiceProvider': 'Add Service Provider',
      'addUnit': 'Add Unit',
      'editUnit': 'Edit Unit',
      'addProject': 'Add Project',
      'editProject': 'Edit Project',
      'addDeveloper': 'Add Developer',
      'editDeveloper': 'Edit Developer',
      'addOwner': 'Add Owner',
      'editOwner': 'Edit Owner',
      'editProduct': 'Edit Product',
      'editProductCategory': 'Edit Product Category',
      'editSupplier': 'Edit Supplier',
      'editService': 'Edit Service',
      'editServicePackage': 'Edit Service Package',
      'editServiceProvider': 'Edit Service Provider',
      'selectNumberToCall': 'Select number to Call',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'assign': 'Assign',
      'assignLead': 'Assign Lead',
      'unassign': 'Unassign',
      'selectEmployee': 'Select Employee',
      'pleaseSelectEmployee': 'Please select an employee',
      'unassignedYet': 'Unassigned Yet',
      'noAnswer': 'No answer',
      'noFeedback': 'No Feedback',
      'noAction': 'No Action',
      'qualified': 'qualified',
      'leadProfile': 'Lead Profile',
      'leadInfo': 'Lead Info',
      'status': 'Status',
      'assignedTo': 'Assigned To',
      'budget': 'Budget',
      'type': 'Type',
      'fresh': 'fresh',
      'channel': 'Channel',
      'jobCategory': 'Job Category',
      'address': 'Address',
      'contacts': 'Contacts',
      'phone': 'Phone',
      'telephone': 'Telephone',
      'communicationWay': 'Communication way',
      'call': 'call',
      'whatsapp': 'WhatsApp',
      'activityInfo': 'Activity Info',
      'cancelReason': 'Cancel Reason',
      'lastReminderDate': 'Last Reminder Date',
      'lastActionDate': 'Last Action Date',
      'dateAdded': 'Date Added',
      'project': 'Project',
      'unit': 'Unit',
      'priority': 'Priority',
      'low': 'low',
      'notes': 'Notes',
      'history': 'History',
      'deals': 'Deals',
      'pending': 'Pending',
      'completed': 'Completed',
      'meeting': 'Meeting',
      'reminder': 'Reminder',
      'outOfService': 'Out of Service',
      'cancellation': 'Cancellation',
      'actionType': 'Action type',
      'selectItem': 'Select item',
      'version': 'Version',
      'logout': 'Logout',
      'english': 'English',
      'inventory': 'Inventory',
      'developers': 'Developers',
      'projects': 'Projects',
      'units': 'Units',
      'owners': 'Owners',
      'services': 'Services',
      'servicePackages': 'Service Packages',
      'serviceProviders': 'Service Providers',
      'products': 'Products',
      'productCategories': 'Product Categories',
      'suppliers': 'Suppliers',
      'errorLogs': 'Error Logs',
      'viewErrorLogs': 'View Error Logs',
      'clearLogs': 'Clear Logs',
      'clearLogsConfirm': 'Are you sure you want to clear all error logs?',
      'clear': 'Clear',
      'noErrors': 'No errors logged yet',
      'errors': 'error(s)',
      'tapToViewDetails': 'Tap on any error to view details and copy',
      'logCopied': 'Error log copied to clipboard',
      'logsCopied': 'All logs copied to clipboard',
      'copy': 'Copy',
      'noDealsFound': 'No deals found',
      'pleaseEnterUsername': 'Please enter username',
      'pleaseEnterPassword': 'Please enter password',
      'selectReminder': 'Select Reminder',
      'removeReminder': 'Remove Reminder',
      'actionAdded': 'Action added successfully',
      'addLeadComingSoon': 'Add lead feature coming soon',
      'editLeadComingSoon': 'Edit lead feature coming soon',
      'assignLeadComingSoon': 'Assign lead feature coming soon',
      'deleteLead': 'Delete Lead',
      'deleteLeadConfirm': 'Are you sure you want to delete this lead?',
      'deleteLeadComingSoon': 'Delete lead feature coming soon',
      'filterComingSoon': 'Filter feature coming soon',
      'dealsComingSoon': 'Deals feature coming soon',
      'developersComingSoon': 'Developers feature coming soon',
      'projectsComingSoon': 'Projects feature coming soon',
      'unitsComingSoon': 'Units feature coming soon',
      'ownersComingSoon': 'Owners feature coming soon',
      'servicesComingSoon': 'Services feature coming soon',
      'servicePackagesComingSoon': 'Service Packages feature coming soon',
      'serviceProvidersComingSoon': 'Service Providers feature coming soon',
      'productsComingSoon': 'Products feature coming soon',
      'productCategoriesComingSoon': 'Product Categories feature coming soon',
      'suppliersComingSoon': 'Suppliers feature coming soon',
      'notificationsComingSoon': 'Notifications feature coming soon',
      'leadCreatedSuccessfully': 'Lead created successfully',
      'leadUpdatedSuccessfully': 'Lead updated successfully',
      'leadDeletedSuccessfully': 'Lead deleted successfully',
      'leadsAssignedSuccessfully': 'Leads assigned successfully',
      'leadsUnassignedSuccessfully': 'Leads unassigned successfully',
      'pleaseEnterClientName': 'Please enter client name',
      'leadsCount': 'Leads count',
      'createNewLead': 'Create New Lead',
      'editLead': 'Edit Lead',
      'leadInformation': 'Lead Information',
      'pleaseFixErrors': 'Please fix the following errors:',
      'nameRequired': 'Name is required',
      'phoneNumberRequired': 'At least one phone number is required',
      'communicationWayRequired': 'Communication channel is required',
      'statusRequired': 'Status is required',
      'priorityRequired': 'Priority is required',
      'typeRequired': 'Type is required',
      'createLead': 'Create Lead',
      'filter': 'Filter',
      'apply': 'Apply',
      'all': 'All',
      'enterClientName': 'Enter client name',
      'enterBudget': 'Enter budget',
      'enterPhoneNumber': 'Enter phone number',
      'unassigned': 'Unassigned',
      'notAssigned': 'Not assigned',
      'assigned': 'Assigned',
      'notSpecified': 'Not specified',
      'cold': 'Cold',
      'high': 'High',
      'medium': 'Medium',
      'clientName': 'Client Name',
      'phoneNumbers': 'Phone Numbers',
      'saveChanges': 'Save Changes',
      'failedToLoadData': 'Failed to load data',
      'noLeadsFound': 'No leads found',
      'addPhoneNumber': 'Add Phone',
      'phoneTypeMobile': 'Mobile',
      'phoneTypeHome': 'Home',
      'phoneTypeWork': 'Work',
      'phoneTypeOther': 'Other',
      'noInternetConnection': 'No Internet Connection',
      'noInternetMessage':
          'Please check your internet connection and try again',
      'connectionError': 'Connection Error',
      'connectionErrorMessage':
          'Unable to connect to the server. Please try again later',
      'errorOccurred': 'An error occurred',
      'tryAgain': 'Try Again',
      'primary': 'Primary',
      'selectCountry': 'Select Country',
      'language': 'Language',
      'arabic': 'Arabic',
      'calendar': 'Calendar',
      'more': 'More',
      'appSettings': 'App settings and preferences',
      'viewEditProfile': 'View and edit your profile',
      'about': 'About',
      'appInfo': 'App version and information',
      'aboutComingSoon': 'About feature coming soon',
      'refresh': 'Refresh',
      'noEvents': 'No events for this date',
      'theme': 'Theme',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'switchToEnglish': 'Switch to English',
      'switchToArabic': 'Switch to Arabic',
      'switchToDarkMode': 'Switch to Dark Mode',
      'switchToLightMode': 'Switch to Light Mode',
      'username': 'Username',
      'password': 'Password',
      'profile': 'Profile',
      'profileSettings': 'Profile Settings',
      'firstName': 'First Name',
      'lastName': 'Last Name',
      'firstNameRequired': 'First name is required',
      'lastNameRequired': 'Last name is required',
      'phoneRequired': 'Phone is required',
      'email': 'Email',
      'clickToChangePhoto': 'Click to change photo',
      'chooseFromGallery': 'Choose from Gallery',
      'takePhoto': 'Take Photo',
      'saveProfile': 'Save Profile',
      'profileUpdatedSuccessfully': 'Profile updated successfully!',
      'loading': 'Loading...',
      'tapToEditProfile': 'Tap to edit profile',
      'logoutConfirmTitle': 'Confirm Logout',
      'logoutConfirmMessage': 'Are you sure you want to logout?',
      'twoFactorAuthTitle': 'Two-Factor Authentication',
      'enter2FACode': 'Enter the 6-digit code sent to your email',
      'twoFactorCodeLabel': 'Verification Code',
      'pleaseEnter2FACode':
          'Please enter the 6-digit two-factor authentication code',
      'twoFactorCodeSent':
          'Two-factor authentication code has been sent to your email',
      'twoFactorCodeExpired':
          'Two-factor authentication code has expired. Please request a new one',
      'twoFactorCodeInvalid': 'Invalid two-factor authentication code',
      'twoFactorAuthFailed': 'Failed to verify two-factor authentication code',
      'resendCode': 'Resend Code',
      'resendCodeIn': 'Resend code in',
      'seconds': 'seconds',
      'pleaseWaitBeforeResend': 'Please wait before resending',
      'verify': 'Verify',
      'backToLogin': 'Back to Login',
      'didntReceiveCode': "Didn't receive code?",
      'accountTemporarilyInactive': 'Your account is temporarily inactive',
      'noActiveSubscription': 'No active subscription found',
      'invalidCredentials':
          'Invalid credentials. Please go back and check your username and password.',
      'userNotFound': 'User not found',
      'subscriptionNotActive':
          'Your subscription is not active. Please contact support or complete your payment to access the system.',
      'anErrorOccurred': 'An error occurred. Please try again.',
      // Settings
      'settings': 'Settings',
      'general': 'General',
      'channels': 'Channels',
      'stages': 'Stages',
      'statuses': 'Statuses',
      'activeChannels': 'Active Channels',
      'leadStages': 'Lead Stages',
      'availableStatuses': 'Available Statuses',
      'addChannel': 'Add Channel',
      'editChannel': 'Edit Channel',
      'deleteChannel': 'Delete Channel',
      'confirmDeleteChannel': 'Are you sure you want to delete this channel?',
      'channelCreatedSuccessfully': 'Channel created successfully',
      'channelUpdatedSuccessfully': 'Channel updated successfully',
      'channelDeletedSuccessfully': 'Channel deleted successfully',
      'addStage': 'Add Stage',
      'editStage': 'Edit Stage',
      'deleteStage': 'Delete Stage',
      'confirmDeleteStage': 'Are you sure you want to delete this stage?',
      'stageCreatedSuccessfully': 'Stage created successfully',
      'stageUpdatedSuccessfully': 'Stage updated successfully',
      'stageDeletedSuccessfully': 'Stage deleted successfully',
      'stageName': 'Stage Name',
      'addStatus': 'Add Status',
      'editStatus': 'Edit Status',
      'deleteStatus': 'Delete Status',
      'confirmDeleteStatus': 'Are you sure you want to delete this status?',
      'statusCreatedSuccessfully': 'Status created successfully',
      'statusUpdatedSuccessfully': 'Status updated successfully',
      'statusDeletedSuccessfully': 'Status deleted successfully',
      'noChannelsAvailable': 'No channels available',
      'noStagesFound': 'No stages found',
      'noStatusesFound': 'No statuses found',
      'autoAdvance': 'Auto Advance',
      'selectColor': 'Select Color',
      'followUp': 'Follow Up',
      'default': 'Default',
      'hidden': 'Hidden',
      'cannotDeleteDefault': 'Cannot delete default status',
      'description': 'Description',
      'color': 'Color',
      'required': 'Required',
      'codeRequired': 'Code is required',
      'developerRequired': 'Developer is required',
      'projectRequired': 'Project is required',
      'bedroomsRequired': 'Bedrooms is required',
      'bathroomsRequired': 'Bathrooms is required',
      'invalidNumber': 'Invalid number',
      'category': 'Category',
      'parentCategory': 'Parent Category',
      'name': 'Name',
      'active': 'Active',
      'inactive': 'Inactive',
      'closed': 'Closed',
      'create': 'Create',
      'update': 'Update',
      'retry': 'Retry',
      // Channel Types
      'web': 'Web',
      'social': 'Social',
      'advertising': 'Advertising',
      'channelTypeWeb': 'Web',
      'channelTypeSocial': 'Social',
      'channelTypeAdvertising': 'Advertising',
      'channelTypeEmail': 'Email',
      'channelTypePhone': 'Phone',
      'channelTypeSMS': 'SMS',
      'channelTypeWhatsApp': 'WhatsApp',
      'channelTypeTelegram': 'Telegram',
      'channelTypeInstagram': 'Instagram',
      'channelTypeFacebook': 'Facebook',
      'channelTypeLinkedIn': 'LinkedIn',
      'channelTypeTwitter': 'Twitter',
      'channelTypeTikTok': 'TikTok',
      'channelTypeYouTube': 'YouTube',
      'channelTypeOther': 'Other',
      'telegram': 'Telegram',
      'instagram': 'Instagram',
      'facebook': 'Facebook',
      'linkedin': 'LinkedIn',
      'twitter': 'Twitter',
      'tiktok': 'TikTok',
      'youtube': 'YouTube',
      'other': 'Other',
      'none': 'None',
      // Error messages for modals
      'failedToCreateChannel': 'Failed to create channel',
      'failedToUpdateChannel': 'Failed to update channel',
      'failedToDeleteChannel': 'Failed to delete channel',
      'failedToCreateStage': 'Failed to create stage',
      'failedToUpdateStage': 'Failed to update stage',
      'failedToDeleteStage': 'Failed to delete stage',
      'failedToCreateStatus': 'Failed to create status',
      'failedToUpdateStatus': 'Failed to update status',
      'failedToDeleteStatus': 'Failed to delete status',
      'failedToLoadChannels': 'Failed to load channels',
      'failedToLoadStages': 'Failed to load stages',
      'failedToLoadStatuses': 'Failed to load statuses',
      'setAsDefault': 'Set as Default',
      'setAsDefaultMessage': 'There is already a default status',
      'setAsDefaultMessage2':
          'Setting this status as default will unset the previous default. Do you want to continue?',
      'continue': 'Continue',
      'filterOptions': 'Filter Options',
      'byStatus': 'By Status',
      'byType': 'By Type',
      'byAssignee': 'By Assignee',
      // Inventory - Real Estate
      'noUnitsFound': 'No units found',
      'noProjectsFound': 'No projects found',
      'noDevelopersFound': 'No developers found',
      'noOwnersFound': 'No owners found',
      'unitDeleted': 'Unit deleted',
      'unitCreated': 'Unit created successfully',
      'unitUpdated': 'Unit updated successfully',
      'deleteUnit': 'Delete Unit',
      'confirmDeleteUnit': 'Are you sure you want to delete',
      'projectDeleted': 'Project deleted',
      'projectCreated': 'Project created successfully',
      'projectUpdated': 'Project updated successfully',
      'deleteProject': 'Delete Project',
      'confirmDeleteProject': 'Are you sure you want to delete',
      'developerDeleted': 'Developer deleted',
      'developerCreated': 'Developer created successfully',
      'developerUpdated': 'Developer updated successfully',
      'deleteDeveloper': 'Delete Developer',
      'confirmDeleteDeveloper': 'Are you sure you want to delete',
      'ownerDeleted': 'Owner deleted',
      'ownerCreated': 'Owner created successfully',
      'ownerUpdated': 'Owner updated successfully',
      'deleteOwner': 'Delete Owner',
      'confirmDeleteOwner': 'Are you sure you want to delete',
      'sold': 'Sold',
      'available': 'Available',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'district': 'District',
      'zone': 'Zone',
      'city': 'City',
      'developer': 'Developer',
      'finishing': 'Finishing',
      'apartment': 'Apartment',
      'villa': 'Villa',
      'finished': 'Finished',
      'semiFinished': 'Semi-Finished',
      'paymentMethod': 'Payment Method',
      'cannotMakeCall': 'Cannot make call',
      // Inventory - Services
      'noServicesFound': 'No services found',
      'noServicePackagesFound': 'No service packages found',
      'noServiceProvidersFound': 'No service providers found',
      'serviceDeleted': 'Service deleted',
      'serviceCreated': 'Service created successfully',
      'serviceUpdated': 'Service updated successfully',
      'deleteService': 'Delete Service',
      'confirmDeleteService': 'Are you sure you want to delete',
      'packageDeleted': 'Package deleted',
      'packageCreated': 'Package created successfully',
      'packageUpdated': 'Package updated successfully',
      'deleteServicePackage': 'Delete Service Package',
      'confirmDeleteServicePackage': 'Are you sure you want to delete',
      'providerDeleted': 'Provider deleted',
      'providerCreated': 'Provider created successfully',
      'providerUpdated': 'Provider updated successfully',
      'deleteServiceProvider': 'Delete Service Provider',
      'confirmDeleteServiceProvider': 'Are you sure you want to delete',
      'provider': 'Provider',
      'duration': 'Duration',
      'rating': 'Rating',
      // Inventory - Products
      'noProductsFound': 'No products found',
      'noProductCategoriesFound': 'No product categories found',
      'noSuppliersFound': 'No suppliers found',
      'productDeleted': 'Product deleted',
      'productCreated': 'Product created successfully',
      'productUpdated': 'Product updated successfully',
      'deleteProduct': 'Delete Product',
      'confirmDeleteProduct': 'Are you sure you want to delete',
      'categoryDeleted': 'Category deleted',
      'categoryCreated': 'Category created successfully',
      'categoryUpdated': 'Category updated successfully',
      'deleteProductCategory': 'Delete Category',
      'confirmDeleteProductCategory': 'Are you sure you want to delete',
      'supplierDeleted': 'Supplier deleted',
      'supplierCreated': 'Supplier created successfully',
      'supplierUpdated': 'Supplier updated successfully',
      'deleteSupplier': 'Delete Supplier',
      'confirmDeleteSupplier': 'Are you sure you want to delete',
      'cost': 'Cost',
      'price': 'Price',
      'stock': 'Stock',
      'sku': 'SKU',
      'supplier': 'Supplier',
      'specialization': 'Specialization',
      'contactPerson': 'Contact Person',
      'properties': 'Properties',
      // Deals
      'dealId': 'Deal ID',
      'stage': 'Stage',
      'value': 'Value',
      'startDate': 'Start Date',
      'closedDate': 'Closed Date',
      'inProgress': 'In Progress',
      'onHold': 'On Hold',
      'won': 'Won',
      'lost': 'Lost',
      'cancelled': 'Cancelled',
      'reservation': 'Reservation',
      'contracted': 'Contracted',
      'cash': 'Cash',
      'installment': 'Installment',
      'personnelInformation': 'Personnel Information',
      'financialInformation': 'Financial Information',
      'deleteDeal': 'Delete Deal',
      'confirmDeleteDeal': 'Are you sure you want to delete the deal for',
      'dealDeletedSuccessfully': 'Deal deleted successfully',
      'failedToDeleteDeal': 'Failed to delete deal',
      'createDeal': 'Create Deal',
      'dealCreatedSuccessfully': 'Deal created successfully',
      'failedToCreateDeal': 'Failed to create deal',
      'failedToUpdateDeal': 'Failed to update deal',
      'filterDeals': 'Filter Deals',
      'viewDealComingSoon': 'View deal feature coming soon',
      'editDealComingSoon': 'Edit deal feature coming soon',
      'view': 'View',
      'reset': 'Reset',
      'applyFilters': 'Apply Filters',
      'searchByClientNameOrId': 'Search by client name or ID',
      'valueRangeStart': 'Value Range Start',
      'valueRangeEnd': 'Value Range End',
      'eg500000': 'e.g. 500000',
      'eg1000000': 'e.g. 1000000',
      'viewDeal': 'View Deal',
      'editDeal': 'Edit Deal',
      'dealInformation': 'Deal Information',
      'realEstateInformation': 'Real Estate Information',
      'basicInformation': 'Basic Information',
      'dates': 'Dates',
      'originalValue': 'Original Value',
      'discountPercentage': 'Discount Percentage',
      'discountAmount': 'Discount Amount',
      'totalValue': 'Total Value',
      'salesCommissionPercentage': 'Sales Commission Percentage',
      'salesCommissionAmount': 'Sales Commission Amount',
      'timestamps': 'Timestamps',
      'createdAt': 'Created At',
      'updatedAt': 'Updated At',
      'lead': 'Lead',
      'employee': 'Employee',
      'startedBy': 'Started By',
      'closedBy': 'Closed By',
      'dealUpdatedSuccessfully': 'Deal updated successfully',
      // Validation messages
      'priceRequired': 'Price is required',
      'invalidPrice': 'Invalid price',
      'costRequired': 'Cost is required',
      'invalidCost': 'Invalid cost',
      'stockRequired': 'Stock is required',
      'invalidStock': 'Invalid stock',
      'categoryRequired': 'Category is required',
      'leadRequired': 'Lead is required',
      'valueRequired': 'Value is required and must be greater than 0',
      'invalidValue': 'Invalid value',
      'unitRequired': 'Unit is required',
      'supplierRequired': 'Supplier is required',
      'serviceRequired': 'Service is required',
      'providerRequired': 'Provider is required',
      'packageRequired': 'Package is required',
      'ownerRequired': 'Owner is required',
      'channelNameRequired': 'Channel name is required',
      'stageNameRequired': 'Stage name is required',
      'statusNameRequired': 'Status name is required',
      'invalidEmail': 'Invalid email address',
      'emailRequired': 'Email is required',
      'submit': 'Submit',
      'addNewLead': 'Add New Lead',
      'editClient': 'Edit Client',
    },
    'ar': {
      // Common
      "signIn": "تسجيل الدخول",
      'appName': 'LOOP CRM',
      'welcome': 'مرحباً بك في LOOP CRM',
      'manageLeadsInventory': 'إدارة العملاء والمخزون',
      'home': 'الرئيسية',
      'leads': 'العملاء',
      'allLeads': 'جميع العملاء',
      'freshLeads': 'عملاء جدد',
      'coldLeads': 'عملاء محتملين',
      'untouched': 'غير معالج',
      'touched': 'معالج',
      'following': 'متابع',
      'goodMorning': 'صباح الخير',
      'readyForWork': 'جاهز للعمل، اجعل العملاء سعداء!',
      'typeToSearch': 'اكتب للبحث...',
      'add': 'إضافة',
      'addAction': 'إضافة إجراء',
      'addProduct': 'إضافة منتج',
      'addProductCategory': 'إضافة فئة منتج',
      'addSupplier': 'إضافة مورد',
      'addService': 'إضافة خدمة',
      'addServicePackage': 'إضافة باقة خدمة',
      'addServiceProvider': 'إضافة مقدم خدمة',
      'addUnit': 'إضافة وحدة',
      'editUnit': 'تعديل وحدة',
      'addProject': 'إضافة مشروع',
      'editProject': 'تعديل مشروع',
      'addDeveloper': 'إضافة مطور',
      'editDeveloper': 'تعديل مطور',
      'addOwner': 'إضافة مالك',
      'editOwner': 'تعديل مالك',
      'editProduct': 'تعديل منتج',
      'editProductCategory': 'تعديل فئة منتج',
      'editSupplier': 'تعديل مورد',
      'editService': 'تعديل خدمة',
      'editServicePackage': 'تعديل باقة خدمة',
      'editServiceProvider': 'تعديل مقدم خدمة',
      'selectNumberToCall': 'اختر رقم للاتصال',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit': 'تعديل',
      'delete': 'حذف',
      'assign': 'تعيين',
      'assignLead': 'تعيين عميل',
      'unassign': 'إلغاء التعيين',
      'selectEmployee': 'اختر موظف',
      'pleaseSelectEmployee': 'الرجاء اختيار موظف',
      'unassignedYet': 'غير معين بعد',
      'noAnswer': 'لا إجابة',
      'noFeedback': 'لا تعليق',
      'noAction': 'لا إجراء',
      'qualified': 'مؤهل',
      'leadProfile': 'ملف العميل',
      'leadInfo': 'معلومات العميل',
      'status': 'الحالة',
      'assignedTo': 'معين إلى',
      'budget': 'الميزانية',
      'type': 'النوع',
      'fresh': 'جديد',
      'channel': 'القناة',
      'jobCategory': 'فئة الوظيفة',
      'address': 'العنوان',
      'contacts': 'جهات الاتصال',
      'phone': 'الهاتف',
      'telephone': 'الهاتف الأرضي',
      'communicationWay': 'طريقة التواصل',
      'call': 'مكالمة',
      'whatsapp': 'واتساب',
      'activityInfo': 'معلومات النشاط',
      'cancelReason': 'سبب الإلغاء',
      'lastReminderDate': 'تاريخ آخر تذكير',
      'lastActionDate': 'تاريخ آخر إجراء',
      'dateAdded': 'تاريخ الإضافة',
      'project': 'المشروع',
      'unit': 'الوحدة',
      'priority': 'الأولوية',
      'low': 'منخفضة',
      'notes': 'ملاحظات',
      'history': 'السجل',
      'deals': 'الصفقات',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'meeting': 'اجتماع',
      'reminder': 'تذكير',
      'outOfService': 'خارج الخدمة',
      'cancellation': 'إلغاء',
      'calendar': 'التقويم',
      'more': 'المزيد',
      'appSettings': 'إعدادات التطبيق والتفضيلات',
      'viewEditProfile': 'عرض وتعديل الملف الشخصي',
      'about': 'حول',
      'appInfo': 'إصدار التطبيق والمعلومات',
      'aboutComingSoon': 'ميزة حول قريباً',
      'refresh': 'تحديث',
      'noEvents': 'لا توجد أحداث في هذا التاريخ',
      'actionType': 'نوع الإجراء',
      'selectItem': 'اختر عنصر',
      'version': 'الإصدار',
      'logout': 'تسجيل الخروج',
      'english': 'الإنجليزية',
      'inventory': 'المخزون',
      'developers': 'المطورون',
      'projects': 'المشاريع',
      'units': 'الوحدات',
      'owners': 'الملاك',
      'services': 'الخدمات',
      'servicePackages': 'باقات الخدمات',
      'serviceProviders': 'مقدمو الخدمات',
      'products': 'المنتجات',
      'productCategories': 'فئات المنتجات',
      'suppliers': 'الموردون',
      'errorLogs': 'سجل الأخطاء',
      'viewErrorLogs': 'عرض سجل الأخطاء',
      'clearLogs': 'مسح السجل',
      'clearLogsConfirm': 'هل أنت متأكد من مسح جميع سجلات الأخطاء؟',
      'clear': 'مسح',
      'noErrors': 'لا توجد أخطاء مسجلة',
      'errors': 'خطأ/أخطاء',
      'tapToViewDetails': 'اضغط على أي خطأ لعرض التفاصيل والنسخ',
      'logCopied': 'تم نسخ سجل الخطأ',
      'logsCopied': 'تم نسخ جميع السجلات',
      'copy': 'نسخ',
      'noDealsFound': 'لا توجد صفقات',
      'pleaseEnterUsername': 'الرجاء إدخال اسم المستخدم',
      'pleaseEnterPassword': 'الرجاء إدخال كلمة المرور',
      'selectReminder': 'اختر تذكير',
      'removeReminder': 'إزالة التذكير',
      'actionAdded': 'تم إضافة الإجراء بنجاح',
      'addLeadComingSoon': 'ميزة إضافة عميل قريباً',
      'editLeadComingSoon': 'ميزة تعديل عميل قريباً',
      'assignLeadComingSoon': 'ميزة تعيين عميل قريباً',
      'deleteLead': 'حذف العميل',
      'deleteLeadConfirm': 'هل أنت متأكد من حذف هذا العميل؟',
      'deleteLeadComingSoon': 'ميزة حذف عميل قريباً',
      'filterComingSoon': 'ميزة التصفية قريباً',
      'dealsComingSoon': 'ميزة الصفقات قريباً',
      'developersComingSoon': 'ميزة المطورين قريباً',
      'projectsComingSoon': 'ميزة المشاريع قريباً',
      'unitsComingSoon': 'ميزة الوحدات قريباً',
      'ownersComingSoon': 'ميزة الملاك قريباً',
      'servicesComingSoon': 'ميزة الخدمات قريباً',
      'servicePackagesComingSoon': 'ميزة باقات الخدمات قريباً',
      'serviceProvidersComingSoon': 'ميزة مقدمي الخدمات قريباً',
      'productsComingSoon': 'ميزة المنتجات قريباً',
      'productCategoriesComingSoon': 'ميزة فئات المنتجات قريباً',
      'suppliersComingSoon': 'ميزة الموردين قريباً',
      'notificationsComingSoon': 'ميزة الإشعارات قريباً',
      'leadCreatedSuccessfully': 'تم إنشاء العميل بنجاح',
      'leadUpdatedSuccessfully': 'تم تحديث العميل بنجاح',
      'leadDeletedSuccessfully': 'تم حذف العميل بنجاح',
      'leadsAssignedSuccessfully': 'تم تعيين العملاء بنجاح',
      'leadsUnassignedSuccessfully': 'تم إلغاء تعيين العملاء بنجاح',
      'pleaseEnterClientName': 'الرجاء إدخال اسم العميل',
      'leadsCount': 'عدد العملاء',
      'createNewLead': 'إنشاء عميل جديد',
      'editLead': 'تعديل عميل',
      'leadInformation': 'معلومات العميل',
      'pleaseFixErrors': 'الرجاء إصلاح الأخطاء التالية:',
      'nameRequired': 'الاسم مطلوب',
      'phoneNumberRequired': 'رقم هاتف واحد على الأقل مطلوب',
      'communicationWayRequired': 'قناة التواصل مطلوبة',
      'statusRequired': 'الحالة مطلوبة',
      'priorityRequired': 'الأولوية مطلوبة',
      'typeRequired': 'النوع مطلوب',
      'createLead': 'إنشاء عميل',
      'filter': 'تصفية',
      'apply': 'تطبيق',
      'all': 'الكل',
      'enterClientName': 'أدخل اسم العميل',
      'enterBudget': 'أدخل الميزانية',
      'enterPhoneNumber': 'أدخل رقم الهاتف',
      'unassigned': 'غير معين',
      'notAssigned': 'غير معين',
      'assigned': 'معين',
      'notSpecified': 'غير محدد',
      'cold': 'محتمل',
      'high': 'عالية',
      'medium': 'متوسطة',
      'clientName': 'اسم العميل',
      'phoneNumbers': 'أرقام الهواتف',
      'saveChanges': 'حفظ التغييرات',
      'failedToLoadData': 'فشل تحميل البيانات',
      'noLeadsFound': 'لم يتم العثور على عملاء',
      'addPhoneNumber': 'إضافة هاتف',
      'phoneTypeMobile': 'جوال',
      'phoneTypeHome': 'منزل',
      'phoneTypeWork': 'عمل',
      'phoneTypeOther': 'أخرى',
      'noInternetConnection': 'لا يوجد اتصال بالإنترنت',
      'noInternetMessage': 'يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى',
      'connectionError': 'خطأ في الاتصال',
      'connectionErrorMessage':
          'تعذر الاتصال بالخادم. يرجى المحاولة مرة أخرى لاحقاً',
      'errorOccurred': 'حدث خطأ',
      'tryAgain': 'حاول مرة أخرى',
      'primary': 'أساسي',
      'selectCountry': 'اختر الدولة',
      'language': 'اللغة',
      'arabic': 'العربية',
      'theme': 'المظهر',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'switchToEnglish': 'التبديل إلى الإنجليزية',
      'switchToArabic': 'التبديل إلى العربية',
      'switchToDarkMode': 'التبديل إلى الوضع الداكن',
      'switchToLightMode': 'التبديل إلى الوضع الفاتح',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'profile': 'الملف الشخصي',
      'profileSettings': 'إعدادات الملف الشخصي',
      'firstName': 'الاسم الأول',
      'lastName': 'اسم العائلة',
      'firstNameRequired': 'الاسم الأول مطلوب',
      'lastNameRequired': 'اسم العائلة مطلوب',
      'phoneRequired': 'رقم الهاتف مطلوب',
      'email': 'البريد الإلكتروني',
      'clickToChangePhoto': 'اضغط لتغيير الصورة',
      'chooseFromGallery': 'اختر من المعرض',
      'takePhoto': 'التقاط صورة',
      'saveProfile': 'حفظ الملف الشخصي',
      'profileUpdatedSuccessfully': 'تم تحديث الملف الشخصي بنجاح!',
      'loading': 'جاري التحميل...',
      'tapToEditProfile': 'اضغط لتعديل الملف الشخصي',
      'logoutConfirmTitle': 'تأكيد تسجيل الخروج',
      'logoutConfirmMessage': 'هل أنت متأكد من تسجيل الخروج؟',
      'twoFactorAuthTitle': 'المصادقة الثنائية',
      'enter2FACode':
          'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك الإلكتروني',
      'twoFactorCodeLabel': 'رمز التحقق',
      'pleaseEnter2FACode':
          'الرجاء إدخال رمز المصادقة الثنائية المكون من 6 أرقام',
      'twoFactorCodeSent':
          'تم إرسال رمز المصادقة الثنائية إلى بريدك الإلكتروني',
      'twoFactorCodeExpired':
          'انتهت صلاحية رمز المصادقة الثنائية. يرجى طلب رمز جديد',
      'twoFactorCodeInvalid': 'رمز المصادقة الثنائية غير صحيح',
      'twoFactorAuthFailed': 'فشل التحقق من رمز المصادقة الثنائية',
      'resendCode': 'إعادة إرسال الرمز',
      'resendCodeIn': 'إعادة الإرسال خلال',
      'seconds': 'ثانية',
      'pleaseWaitBeforeResend': 'يرجى الانتظار قبل إعادة الإرسال',
      'verify': 'تحقق',
      'backToLogin': 'العودة إلى تسجيل الدخول',
      'didntReceiveCode': 'لم تستلم الرمز؟',
      'accountTemporarilyInactive': 'حسابك غير نشط مؤقتاً',
      'noActiveSubscription': 'لا يوجد اشتراك نشط',
      'invalidCredentials':
          'بيانات الاعتماد غير صحيحة. يرجى العودة والتحقق من اسم المستخدم وكلمة المرور.',
      'userNotFound': 'المستخدم غير موجود',
      'subscriptionNotActive':
          'اشتراكك غير نشط. يرجى الاتصال بالدعم أو إتمام الدفع للوصول إلى النظام.',
      'anErrorOccurred': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      // Settings
      'settings': 'الإعدادات',
      'general': 'عام',
      'channels': 'القنوات',
      'stages': 'المراحل',
      'statuses': 'الحالات',
      'activeChannels': 'القنوات النشطة',
      'leadStages': 'مراحل العملاء',
      'availableStatuses': 'الحالات المتاحة',
      'addChannel': 'إضافة قناة',
      'editChannel': 'تعديل قناة',
      'deleteChannel': 'حذف قناة',
      'confirmDeleteChannel': 'هل أنت متأكد من حذف هذه القناة؟',
      'channelCreatedSuccessfully': 'تم إنشاء القناة بنجاح',
      'channelUpdatedSuccessfully': 'تم تحديث القناة بنجاح',
      'channelDeletedSuccessfully': 'تم حذف القناة بنجاح',
      'addStage': 'إضافة مرحلة',
      'editStage': 'تعديل مرحلة',
      'deleteStage': 'حذف مرحلة',
      'confirmDeleteStage': 'هل أنت متأكد من حذف هذه المرحلة؟',
      'stageCreatedSuccessfully': 'تم إنشاء المرحلة بنجاح',
      'stageUpdatedSuccessfully': 'تم تحديث المرحلة بنجاح',
      'stageDeletedSuccessfully': 'تم حذف المرحلة بنجاح',
      'stageName': 'اسم المرحلة',
      'addStatus': 'إضافة حالة',
      'editStatus': 'تعديل حالة',
      'deleteStatus': 'حذف حالة',
      'confirmDeleteStatus': 'هل أنت متأكد من حذف هذه الحالة؟',
      'statusCreatedSuccessfully': 'تم إنشاء الحالة بنجاح',
      'statusUpdatedSuccessfully': 'تم تحديث الحالة بنجاح',
      'statusDeletedSuccessfully': 'تم حذف الحالة بنجاح',
      'noChannelsAvailable': 'لا توجد قنوات متاحة',
      'noStagesFound': 'لم يتم العثور على مراحل',
      'noStatusesFound': 'لم يتم العثور على حالات',
      'autoAdvance': 'تقدم تلقائي',
      'selectColor': 'اختر اللون',
      'followUp': 'متابعة',
      'default': 'افتراضي',
      'hidden': 'مخفي',
      'cannotDeleteDefault': 'لا يمكن حذف الحالة الافتراضية',
      'description': 'الوصف',
      'color': 'اللون',
      'required': 'مطلوب',
      'codeRequired': 'الكود مطلوب',
      'developerRequired': 'المطور مطلوب',
      'projectRequired': 'المشروع مطلوب',
      'bedroomsRequired': 'عدد غرف النوم مطلوب',
      'bathroomsRequired': 'عدد الحمامات مطلوب',
      'invalidNumber': 'رقم غير صحيح',
      'category': 'الفئة',
      'parentCategory': 'الفئة الرئيسية',
      'name': 'الاسم',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'closed': 'مغلق',
      'create': 'إنشاء',
      'update': 'تحديث',
      'retry': 'إعادة المحاولة',
      // Channel Types
      'web': 'ويب',
      'social': 'اجتماعي',
      'advertising': 'إعلان',
      'channelTypeWeb': 'ويب',
      'channelTypeSocial': 'اجتماعي',
      'channelTypeAdvertising': 'إعلان',
      'channelTypeEmail': 'بريد إلكتروني',
      'channelTypePhone': 'هاتف',
      'channelTypeSMS': 'رسالة نصية',
      'channelTypeWhatsApp': 'واتساب',
      'channelTypeTelegram': 'تيليجرام',
      'channelTypeInstagram': 'إنستغرام',
      'channelTypeFacebook': 'فيسبوك',
      'channelTypeLinkedIn': 'لينكد إن',
      'channelTypeTwitter': 'تويتر',
      'channelTypeTikTok': 'تيك توك',
      'channelTypeYouTube': 'يوتيوب',
      'channelTypeOther': 'أخرى',
      'telegram': 'تيليجرام',
      'instagram': 'إنستغرام',
      'facebook': 'فيسبوك',
      'linkedin': 'لينكد إن',
      'twitter': 'تويتر',
      'tiktok': 'تيك توك',
      'youtube': 'يوتيوب',
      'other': 'أخرى',
      'none': 'لا شيء',
      // Error messages for modals
      'failedToCreateChannel': 'فشل إنشاء القناة',
      'failedToUpdateChannel': 'فشل تحديث القناة',
      'failedToDeleteChannel': 'فشل حذف القناة',
      'failedToCreateStage': 'فشل إنشاء المرحلة',
      'failedToUpdateStage': 'فشل تحديث المرحلة',
      'failedToDeleteStage': 'فشل حذف المرحلة',
      'failedToCreateStatus': 'فشل إنشاء الحالة',
      'failedToUpdateStatus': 'فشل تحديث الحالة',
      'failedToDeleteStatus': 'فشل حذف الحالة',
      'failedToLoadChannels': 'فشل تحميل القنوات',
      'failedToLoadStages': 'فشل تحميل المراحل',
      'failedToLoadStatuses': 'فشل تحميل الحالات',
      'setAsDefault': 'تعيين كافتراضي',
      'setAsDefaultMessage': 'يوجد بالفعل حالة افتراضية',
      'setAsDefaultMessage2':
          'تعيين هذه الحالة كافتراضية سيلغي الحالة الافتراضية السابقة. هل تريد المتابعة؟',
      'continue': 'متابعة',
      'filterOptions': 'خيارات التصفية',
      'byStatus': 'حسب الحالة',
      'byType': 'حسب النوع',
      'byAssignee': 'حسب المعين',
      // Inventory - Real Estate
      'noUnitsFound': 'لم يتم العثور على وحدات',
      'noProjectsFound': 'لم يتم العثور على مشاريع',
      'noDevelopersFound': 'لم يتم العثور على مطورين',
      'noOwnersFound': 'لم يتم العثور على ملاك',
      'unitDeleted': 'تم حذف الوحدة',
      'unitCreated': 'تم إنشاء الوحدة بنجاح',
      'unitUpdated': 'تم تحديث الوحدة بنجاح',
      'deleteUnit': 'حذف الوحدة',
      'confirmDeleteUnit': 'هل أنت متأكد من حذف',
      'projectDeleted': 'تم حذف المشروع',
      'projectCreated': 'تم إنشاء المشروع بنجاح',
      'projectUpdated': 'تم تحديث المشروع بنجاح',
      'deleteProject': 'حذف المشروع',
      'confirmDeleteProject': 'هل أنت متأكد من حذف',
      'developerDeleted': 'تم حذف المطور',
      'developerCreated': 'تم إنشاء المطور بنجاح',
      'developerUpdated': 'تم تحديث المطور بنجاح',
      'deleteDeveloper': 'حذف المطور',
      'confirmDeleteDeveloper': 'هل أنت متأكد من حذف',
      'ownerDeleted': 'تم حذف المالك',
      'ownerCreated': 'تم إنشاء المالك بنجاح',
      'ownerUpdated': 'تم تحديث المالك بنجاح',
      'deleteOwner': 'حذف المالك',
      'confirmDeleteOwner': 'هل أنت متأكد من حذف',
      'sold': 'مباع',
      'available': 'متاح',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'district': 'الحي',
      'zone': 'المنطقة',
      'city': 'المدينة',
      'developer': 'المطور',
      'finishing': 'التشطيب',
      'apartment': 'شقة',
      'villa': 'فيلا',
      'finished': 'منتهي بالكامل',
      'semiFinished': 'نصف منتهي',
      'paymentMethod': 'طريقة الدفع',
      'cannotMakeCall': 'لا يمكن إجراء المكالمة',
      // Inventory - Services
      'noServicesFound': 'لم يتم العثور على خدمات',
      'noServicePackagesFound': 'لم يتم العثور على باقات خدمات',
      'noServiceProvidersFound': 'لم يتم العثور على مقدمي خدمات',
      'serviceDeleted': 'تم حذف الخدمة',
      'serviceCreated': 'تم إنشاء الخدمة بنجاح',
      'serviceUpdated': 'تم تحديث الخدمة بنجاح',
      'deleteService': 'حذف الخدمة',
      'confirmDeleteService': 'هل أنت متأكد من حذف',
      'packageDeleted': 'تم حذف الباقة',
      'packageCreated': 'تم إنشاء الباقة بنجاح',
      'packageUpdated': 'تم تحديث الباقة بنجاح',
      'deleteServicePackage': 'حذف الباقة',
      'confirmDeleteServicePackage': 'هل أنت متأكد من حذف',
      'providerDeleted': 'تم حذف مقدم الخدمة',
      'providerCreated': 'تم إنشاء مقدم الخدمة بنجاح',
      'providerUpdated': 'تم تحديث مقدم الخدمة بنجاح',
      'deleteServiceProvider': 'حذف مقدم الخدمة',
      'confirmDeleteServiceProvider': 'هل أنت متأكد من حذف',
      'provider': 'مقدم الخدمة',
      'duration': 'المدة',
      'rating': 'التقييم',
      // Inventory - Products
      'noProductsFound': 'لم يتم العثور على منتجات',
      'noProductCategoriesFound': 'لم يتم العثور على فئات منتجات',
      'noSuppliersFound': 'لم يتم العثور على موردين',
      'productDeleted': 'تم حذف المنتج',
      'productCreated': 'تم إنشاء المنتج بنجاح',
      'productUpdated': 'تم تحديث المنتج بنجاح',
      'deleteProduct': 'حذف المنتج',
      'confirmDeleteProduct': 'هل أنت متأكد من حذف',
      'categoryDeleted': 'تم حذف الفئة',
      'categoryCreated': 'تم إنشاء الفئة بنجاح',
      'categoryUpdated': 'تم تحديث الفئة بنجاح',
      'deleteProductCategory': 'حذف الفئة',
      'confirmDeleteProductCategory': 'هل أنت متأكد من حذف',
      'supplierDeleted': 'تم حذف المورد',
      'supplierCreated': 'تم إنشاء المورد بنجاح',
      'supplierUpdated': 'تم تحديث المورد بنجاح',
      'deleteSupplier': 'حذف المورد',
      'confirmDeleteSupplier': 'هل أنت متأكد من حذف',
      'cost': 'التكلفة',
      'price': 'السعر',
      'stock': 'المخزون',
      'sku': 'رمز المنتج',
      'supplier': 'المورد',
      'specialization': 'التخصص',
      'contactPerson': 'الشخص المسؤول',
      'properties': 'العقارات',
      // Deals
      'dealId': 'معرف الصفقة',
      'stage': 'المرحلة',
      'value': 'القيمة',
      'startDate': 'تاريخ البدء',
      'closedDate': 'تاريخ الإغلاق',
      'inProgress': 'قيد التنفيذ',
      'onHold': 'معلقة',
      'won': 'مكتملة',
      'lost': 'فاشلة',
      'cancelled': 'ملغاة',
      'reservation': 'حجز',
      'contracted': 'متعاقد',
      'cash': 'نقدي',
      'installment': 'تقسيط',
      'personnelInformation': 'معلومات الموظفين',
      'financialInformation': 'المعلومات المالية',
      'deleteDeal': 'حذف الصفقة',
      'confirmDeleteDeal': 'هل أنت متأكد من حذف الصفقة ل',
      'dealDeletedSuccessfully': 'تم حذف الصفقة بنجاح',
      'failedToDeleteDeal': 'فشل حذف الصفقة',
      'createDeal': 'إنشاء صفقة',
      'dealCreatedSuccessfully': 'تم إنشاء الصفقة بنجاح',
      'failedToCreateDeal': 'فشل إنشاء الصفقة',
      'failedToUpdateDeal': 'فشل تحديث الصفقة',
      'filterDeals': 'تصفية الصفقات',
      'viewDealComingSoon': 'ميزة عرض الصفقة قريباً',
      'editDealComingSoon': 'ميزة تعديل الصفقة قريباً',
      'view': 'عرض',
      'reset': 'إعادة تعيين',
      'applyFilters': 'تطبيق التصفية',
      'searchByClientNameOrId': 'البحث باسم العميل أو المعرف',
      'valueRangeStart': 'بداية نطاق القيمة',
      'valueRangeEnd': 'نهاية نطاق القيمة',
      'eg500000': 'مثال: 500000',
      'eg1000000': 'مثال: 1000000',
      'viewDeal': 'عرض الصفقة',
      'editDeal': 'تعديل الصفقة',
      'dealInformation': 'معلومات الصفقة',
      'realEstateInformation': 'معلومات العقارات',
      'basicInformation': 'المعلومات الأساسية',
      'dates': 'التواريخ',
      'originalValue': 'القيمة الأصلية',
      'discountPercentage': 'نسبة الخصم',
      'discountAmount': 'مبلغ الخصم',
      'totalValue': 'القيمة الإجمالية',
      'salesCommissionPercentage': 'نسبة عمولة المبيعات',
      'salesCommissionAmount': 'مبلغ عمولة المبيعات',
      'timestamps': 'الطوابع الزمنية',
      'createdAt': 'تاريخ الإنشاء',
      'updatedAt': 'تاريخ التحديث',
      'lead': 'العميل المحتمل',
      'employee': 'الموظف',
      'startedBy': 'بدأ بواسطة',
      'closedBy': 'أغلق بواسطة',
      'dealUpdatedSuccessfully': 'تم تحديث الصفقة بنجاح',
      // Validation messages
      'priceRequired': 'السعر مطلوب',
      'invalidPrice': 'سعر غير صحيح',
      'costRequired': 'التكلفة مطلوبة',
      'invalidCost': 'تكلفة غير صحيحة',
      'stockRequired': 'المخزون مطلوب',
      'invalidStock': 'مخزون غير صحيح',
      'categoryRequired': 'الفئة مطلوبة',
      'leadRequired': 'العميل مطلوب',
      'valueRequired': 'القيمة مطلوبة ويجب أن تكون أكبر من 0',
      'invalidValue': 'قيمة غير صحيحة',
      'unitRequired': 'الوحدة مطلوبة',
      'supplierRequired': 'المورد مطلوب',
      'serviceRequired': 'الخدمة مطلوبة',
      'providerRequired': 'مقدم الخدمة مطلوب',
      'packageRequired': 'الباقة مطلوبة',
      'ownerRequired': 'المالك مطلوب',
      'channelNameRequired': 'اسم القناة مطلوب',
      'stageNameRequired': 'اسم المرحلة مطلوب',
      'statusNameRequired': 'اسم الحالة مطلوب',
      'invalidEmail': 'عنوان بريد إلكتروني غير صحيح',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'submit': 'إرسال',
      'addNewLead': 'إضافة عميل جديد',
      'editClient': 'تعديل العميل',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  bool get isRTL => locale.languageCode == 'ar';
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
