/// Deal-related UI strings by company specialization (`services`, `products`, `medical`).
/// `real_estate` uses defaults from [AppLocalizations].
typedef DealTermMap = Map<String, String>;

final Map<String, Map<String, DealTermMap>> kDealTerminologyBySpec = {
  'services': {
    'en': {
      'deals': 'Contracts',
      'deal': 'Contract',
      'createDeal': 'Create contract',
      'deleteDeal': 'Delete contract',
      'confirmDeleteDeal': 'Are you sure you want to delete the contract for',
      'dealDeletedSuccessfully': 'Contract deleted successfully',
      'failedToDeleteDeal': 'Failed to delete contract',
      'dealCreatedSuccessfully': 'Contract created successfully',
      'failedToCreateDeal': 'Failed to create contract',
      'failedToUpdateDeal': 'Failed to update contract',
      'filterDeals': 'Filter contracts',
      'viewDeal': 'View contract',
      'editDeal': 'Edit contract',
      'dealInformation': 'Contract information',
      'dealUpdatedSuccessfully': 'Contract updated successfully',
      'dealNotifications': 'Contract notifications',
      'dealCreated': 'Contract created',
      'dealUpdated': 'Contract updated',
      'dealClosed': 'Contract closed',
      'dealReminder': 'Contract reminder',
      'plan_quota_max_deals_exceeded':
          'You have reached your plan contracts limit. Please upgrade your plan to add more contracts.',
      'failedToGetDeals': 'Failed to get contracts',
      'failedToLoadDeals': 'Failed to load contracts',
      'failedToCreateDealWithStatus': 'Failed to create contract with status',
      'failedToUpdateDealWithStatus': 'Failed to update contract with status',
      'failedToDeleteDealWithStatus': 'Failed to delete contract with status',
      'noDealsFound': 'No contracts found',
    },
    'ar': {
      'deals': 'العقود',
      'deal': 'عقد',
      'createDeal': 'إنشاء عقد',
      'deleteDeal': 'حذف العقد',
      'confirmDeleteDeal': 'هل أنت متأكد أنك تريد حذف العقد ل',
      'dealDeletedSuccessfully': 'تم حذف العقد بنجاح',
      'failedToDeleteDeal': 'فشل حذف العقد',
      'dealCreatedSuccessfully': 'تم إنشاء العقد بنجاح',
      'failedToCreateDeal': 'فشل إنشاء العقد',
      'failedToUpdateDeal': 'فشل تحديث العقد',
      'filterDeals': 'تصفية العقود',
      'viewDeal': 'عرض العقد',
      'editDeal': 'تعديل العقد',
      'dealInformation': 'معلومات العقد',
      'dealUpdatedSuccessfully': 'تم تحديث العقد بنجاح',
      'dealNotifications': 'إشعارات العقود',
      'dealCreated': 'عقد جديد',
      'dealUpdated': 'تحديث عقد',
      'dealClosed': 'إغلاق عقد',
      'dealReminder': 'تذكير عقد',
      'plan_quota_max_deals_exceeded':
          'لقد وصلت إلى الحد الأقصى للعقود في خطتك. يرجى ترقية الخطة لإضافة المزيد.',
      'failedToGetDeals': 'فشل الحصول على العقود',
      'failedToLoadDeals': 'فشل تحميل العقود',
      'failedToCreateDealWithStatus': 'فشل إنشاء العقد مع الحالة',
      'failedToUpdateDealWithStatus': 'فشل تحديث العقد مع الحالة',
      'failedToDeleteDealWithStatus': 'فشل حذف العقد مع الحالة',
      'noDealsFound': 'لا توجد عقود',
    },
  },
  'products': {
    'en': {
      'deals': 'Orders',
      'deal': 'Order',
      'createDeal': 'Create order',
      'deleteDeal': 'Delete order',
      'confirmDeleteDeal': 'Are you sure you want to delete the order for',
      'dealDeletedSuccessfully': 'Order deleted successfully',
      'failedToDeleteDeal': 'Failed to delete order',
      'dealCreatedSuccessfully': 'Order created successfully',
      'failedToCreateDeal': 'Failed to create order',
      'failedToUpdateDeal': 'Failed to update order',
      'filterDeals': 'Filter orders',
      'viewDeal': 'View order',
      'editDeal': 'Edit order',
      'dealInformation': 'Order information',
      'dealUpdatedSuccessfully': 'Order updated successfully',
      'dealNotifications': 'Order notifications',
      'dealCreated': 'Order created',
      'dealUpdated': 'Order updated',
      'dealClosed': 'Order closed',
      'dealReminder': 'Order reminder',
      'plan_quota_max_deals_exceeded':
          'You have reached your plan orders limit. Please upgrade your plan to add more orders.',
      'failedToGetDeals': 'Failed to get orders',
      'failedToLoadDeals': 'Failed to load orders',
      'failedToCreateDealWithStatus': 'Failed to create order with status',
      'failedToUpdateDealWithStatus': 'Failed to update order with status',
      'failedToDeleteDealWithStatus': 'Failed to delete order with status',
      'noDealsFound': 'No orders found',
    },
    'ar': {
      'deals': 'الطلبات',
      'deal': 'طلبية',
      'createDeal': 'إنشاء طلبية',
      'deleteDeal': 'حذف الطلبية',
      'confirmDeleteDeal': 'هل أنت متأكد أنك تريد حذف الطلبية ل',
      'dealDeletedSuccessfully': 'تم حذف الطلبية بنجاح',
      'failedToDeleteDeal': 'فشل حذف الطلبية',
      'dealCreatedSuccessfully': 'تم إنشاء الطلبية بنجاح',
      'failedToCreateDeal': 'فشل إنشاء الطلبية',
      'failedToUpdateDeal': 'فشل تحديث الطلبية',
      'filterDeals': 'تصفية الطلبات',
      'viewDeal': 'عرض الطلبية',
      'editDeal': 'تعديل الطلبية',
      'dealInformation': 'معلومات الطلبية',
      'dealUpdatedSuccessfully': 'تم تحديث الطلبية بنجاح',
      'dealNotifications': 'إشعارات الطلبات',
      'dealCreated': 'طلبية جديدة',
      'dealUpdated': 'تحديث طلبية',
      'dealClosed': 'إغلاق طلبية',
      'dealReminder': 'تذكير طلبية',
      'plan_quota_max_deals_exceeded':
          'لقد وصلت إلى الحد الأقصى للطلبات في خطتك. يرجى ترقية الخطة لإضافة المزيد.',
      'failedToGetDeals': 'فشل الحصول على الطلبات',
      'failedToLoadDeals': 'فشل تحميل الطلبات',
      'failedToCreateDealWithStatus': 'فشل إنشاء الطلبية مع الحالة',
      'failedToUpdateDealWithStatus': 'فشل تحديث الطلبية مع الحالة',
      'failedToDeleteDealWithStatus': 'فشل حذف الطلبية مع الحالة',
      'noDealsFound': 'لا توجد طلبات',
    },
  },
  'medical': {
    'en': {
      'deals': 'Treatment plans',
      'deal': 'Treatment plan',
      'createDeal': 'Create treatment plan',
      'deleteDeal': 'Delete treatment plan',
      'confirmDeleteDeal':
          'Are you sure you want to delete the treatment plan for',
      'dealDeletedSuccessfully': 'Treatment plan deleted successfully',
      'failedToDeleteDeal': 'Failed to delete treatment plan',
      'dealCreatedSuccessfully': 'Treatment plan created successfully',
      'failedToCreateDeal': 'Failed to create treatment plan',
      'failedToUpdateDeal': 'Failed to update treatment plan',
      'filterDeals': 'Filter treatment plans',
      'viewDeal': 'View treatment plan',
      'editDeal': 'Edit treatment plan',
      'dealInformation': 'Treatment plan information',
      'dealUpdatedSuccessfully': 'Treatment plan updated successfully',
      'dealNotifications': 'Treatment plan notifications',
      'dealCreated': 'Treatment plan created',
      'dealUpdated': 'Treatment plan updated',
      'dealClosed': 'Treatment plan closed',
      'dealReminder': 'Treatment plan reminder',
      'plan_quota_max_deals_exceeded':
          'You have reached your plan treatment plans limit. Please upgrade your plan to add more.',
      'failedToGetDeals': 'Failed to get treatment plans',
      'failedToLoadDeals': 'Failed to load treatment plans',
      'failedToCreateDealWithStatus':
          'Failed to create treatment plan with status',
      'failedToUpdateDealWithStatus':
          'Failed to update treatment plan with status',
      'failedToDeleteDealWithStatus':
          'Failed to delete treatment plan with status',
      'noDealsFound': 'No treatment plans found',
    },
    'ar': {
      'deals': 'خطط العلاج',
      'deal': 'خطة علاج',
      'createDeal': 'إنشاء خطة علاج',
      'deleteDeal': 'حذف خطة العلاج',
      'confirmDeleteDeal': 'هل أنت متأكد أنك تريد حذف خطة العلاج ل',
      'dealDeletedSuccessfully': 'تم حذف خطة العلاج بنجاح',
      'failedToDeleteDeal': 'فشل حذف خطة العلاج',
      'dealCreatedSuccessfully': 'تم إنشاء خطة العلاج بنجاح',
      'failedToCreateDeal': 'فشل إنشاء خطة العلاج',
      'failedToUpdateDeal': 'فشل تحديث خطة العلاج',
      'filterDeals': 'تصفية خطط العلاج',
      'viewDeal': 'عرض خطة العلاج',
      'editDeal': 'تعديل خطة العلاج',
      'dealInformation': 'معلومات خطة العلاج',
      'dealUpdatedSuccessfully': 'تم تحديث خطة العلاج بنجاح',
      'dealNotifications': 'إشعارات خطط العلاج',
      'dealCreated': 'خطة علاج جديدة',
      'dealUpdated': 'تحديث خطة علاج',
      'dealClosed': 'إغلاق خطة علاج',
      'dealReminder': 'تذكير خطة علاج',
      'plan_quota_max_deals_exceeded':
          'لقد وصلت إلى الحد الأقصى لخطط العلاج في خطتك. يرجى ترقية الخطة لإضافة المزيد.',
      'failedToGetDeals': 'فشل الحصول على خطط العلاج',
      'failedToLoadDeals': 'فشل تحميل خطط العلاج',
      'failedToCreateDealWithStatus': 'فشل إنشاء خطة العلاج مع الحالة',
      'failedToUpdateDealWithStatus': 'فشل تحديث خطة العلاج مع الحالة',
      'failedToDeleteDealWithStatus': 'فشل حذف خطة العلاج مع الحالة',
      'noDealsFound': 'لا توجد خطط علاج',
    },
  },
};

String? dealTerminologyLookup(String? specialization, String localeLang, String key) {
  final spec = (specialization ?? '').toLowerCase();
  final byLang = kDealTerminologyBySpec[spec];
  if (byLang == null) return null;
  final lang = localeLang == 'ar' ? 'ar' : 'en';
  final map = byLang[lang] ?? byLang['en'];
  if (map == null) return null;
  final v = map[key];
  if (v == null || v.isEmpty) return null;
  return v;
}
